mealprep/mealprep/urls.py
import os

from django.contrib import admin
from django.urls import path, include
from recipes.views import custom_handler404


handler404 = custom_handler404

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('recipes.urls')),
    path(r'{}/'.format(os.environ.get('ADMIN_ROUTE')), admin.site.urls),
#    path('admin/', admin.site.urls),
]

mealprep/recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.index, name='index'),
    path('choose', views.choose, name='choose'),
    path('active', views.active, name='active'),
    path('shopping', views.shopping, name='shopping'),
    path('favorite', views.favorite, name='favorite'),
    path('recipe/<int:recipe_id>/', views.recipe, name='recipe'),
    path('favorite_active_update', views.favorite_active_update, name='favorite_active_update'),
    path('shopping_update', views.shopping_update, name='shopping_update')
]

mealprep/recipes/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db.models.functions import Concat
from django.db.models import Sum, Value
from django.db import models


# Recipe related tables
class Recipe(models.Model):

    class DifficultyType(models.TextChoices):
        FACILE = 'Facile'
        INTERMEDIAIRE = 'Intérmediaire'
        DIFFICILE = 'Difficile'

    recipe_id = models.AutoField(primary_key=True)
    recipe_id_hash = models.BigIntegerField()
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=200)
    time_total = models.SmallIntegerField()
    time_prep = models.SmallIntegerField()
    difficulty = models.CharField(max_length=20, choices=DifficultyType.choices)
    meal_type = models.CharField(max_length=50)
    recipe_json = models.CharField(max_length=10000)

    class Meta:
        managed = False
        db_table = 'recipe'

    def __str__(self):
        return f'{self.title} {self.subtitle}'


class Ingredient(models.Model):
    ingredient_id = models.AutoField(primary_key=True)
    ingredient_id_hash = models.BigIntegerField()
    ingredient_name = models.CharField(max_length=200)
    ingredient_class = models.CharField(max_length=200)
    ingredient_type = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'ingredient'

    def __str__(self):
        return self.ingredient_name


class Tag(models.Model):
    tag_id = models.AutoField(primary_key=True)
    tag_name = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'tag'

    def __str__(self):
        return f'{self.tag_name}'


class Tool(models.Model):
    tool_id = models.AutoField(primary_key=True)
    tool_name = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'tool'

    def __str__(self):
        return f'{self.tool_name}'


class RecipeIngredient(models.Model):
    id = models.AutoField(primary_key=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.RESTRICT)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.RESTRICT)
    quantity = models.FloatField()
    quantity_unit = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'recipe_ingredient'

    def __str__(self):
        return f'Recipe: {self.recipe}, ingredient: {self.ingredient}'


class RecipeNutrValue(models.Model):
    recipe = models.OneToOneField(Recipe, on_delete=models.RESTRICT, primary_key=True)
    energie_kj = models.FloatField()
    energie_kcal = models.FloatField()
    matieres_grasses = models.FloatField()
    acides_gras_satures = models.FloatField()
    glucides = models.FloatField()
    sucres = models.FloatField()
    proteines = models.FloatField()
    sel = models.FloatField()

    class Meta:
        managed = False
        db_table = 'recipe_nutr_value'


class RecipeTag(models.Model):
    id = models.AutoField(primary_key=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.RESTRICT)
    tag = models.ForeignKey('Tag', on_delete=models.RESTRICT)

    class Meta:
        managed = False
        db_table = 'recipe_tag'


class RecipeTool(models.Model):
    id = models.AutoField(primary_key=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.RESTRICT)
    tool = models.ForeignKey(Tool, on_delete=models.RESTRICT)

    class Meta:
        managed = False
        db_table = 'recipe_tool'


# User related tables
class User(AbstractUser):
    pass


class UserShoppingList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, null=True)
    status = models.SmallIntegerField(default=0)


class UserActiveRecipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, null=True)


class UserFavoriteRecipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, null=True)

mealprep/recipes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import HttpResponse
from rest_framework.decorators import api_view

from .models import Ingredient, Recipe, RecipeIngredient, UserActiveRecipe, UserFavoriteRecipe, UserShoppingList


@api_view(['GET'])
def custom_handler404(request, exception):
    return render(request, 'recipes/404.html', status=404)


@api_view(['GET'])
@login_required
def index(request) -> redirect:
    """Redirect from index to active."""
    return redirect('recipes:active')


@api_view(['GET'])
@login_required
def choose(request) -> render:
    """List all available recipes sorted my meal type. Can be filtered by total preparation time or meal type."""
    recipes = Recipe.objects.all().order_by('meal_type')
    active_recipes = UserActiveRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    favorite_recipes = UserFavoriteRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    return render(request, 'recipes/choose.html',
                  {
                      'recipes': recipes,
                      'active_recipes': active_recipes,
                      'favorite_recipes': favorite_recipes,
                      'meal_types': recipes.order_by('meal_type').values_list('meal_type', flat=True).distinct(),
                      'prep_times': recipes.order_by('time_total').values_list('time_total', flat=True).distinct()
                  })


@api_view(['GET'])
@login_required
def active(request) -> render:
    """List of user active recipes."""
    recipes = UserActiveRecipe.objects.filter(user_id=request.user.id).select_related('recipe')
    favorite_recipes = UserFavoriteRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    return render(
        request, 'recipes/active.html', {'recipes': recipes, 'favorite_recipes': favorite_recipes}
    )


@api_view(['GET'])
@login_required
def favorite(request) -> render:
    """List of user favorite recipes."""
    favorite_recipes = UserFavoriteRecipe.objects.filter(user_id=request.user.id).select_related('recipe')
    active_recipes = UserActiveRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    return render(
        request, 'recipes/favorite.html', {'favorite_recipes': favorite_recipes, 'active_recipes': active_recipes}
    )


@api_view(['GET'])
@login_required
def shopping(request) -> render:
    """List of ingredients to buy for active recipe(s). Sorted by ingredient category."""
    recipes_list = UserActiveRecipe.objects.filter(user_id=request.user.id).values_list('recipe_id', flat=True)
    ingredients = RecipeIngredient.objects.filter(recipe_id__in=recipes_list).select_related('ingredient')
    ingredients = ingredients.values(
        'ingredient_id', 'ingredient__ingredient_id_hash', 'ingredient__ingredient_name', 'ingredient__ingredient_class',
        'quantity_unit'
    ).order_by().annotate(quantity=Sum("quantity"))
    categories = ["Légumes", "Fruits", "Herbes", "Végétarien", "Conserves", "Graines et Pâtes", "Épices",
                  "Laitier", "Salades", "Pains", "Autre"]
    ingr_dict = {i: ingredients.filter(ingredient__ingredient_class=i) for i in categories if ingredients.filter(ingredient__ingredient_class=i)}
    bought_ingredients = UserShoppingList.objects.filter(user_id=request.user.id, status=1).values_list('ingredient_id', flat=True)
    return render(request, 'recipes/shopping.html', {
        'ingr_dict': ingr_dict, 'categories': categories, 'bought_ingredients': bought_ingredients
    })


@api_view(['GET'])
@login_required
def recipe(request, recipe_id: int) -> render:
    """Recipe page with description, list of ingredients and instructions."""
    recipe_dict = eval(get_object_or_404(Recipe, recipe_id=recipe_id).recipe_json)
    nutr_val_cat = ['Énergie (kJ)', 'Énergie (kcal)', 'Matières grasses', 'dont acides gras saturés',
                    'Glucides', 'dont sucres', 'Protéines', 'Sel']
    unit = ['kJ', 'kcal'] + ['g'] * 5
    nutr_val = zip(nutr_val_cat, recipe_dict['nutritional_val'], unit)
    active_recipes = UserActiveRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    favorite_recipes = UserFavoriteRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    return render(request, 'recipes/recipe.html',
                  {'recipe': recipe_dict,
                   'nutr_val': nutr_val,
                   'active_recipe': recipe_id in active_recipes,
                   'favorite_recipe': recipe_id in favorite_recipes
                   })


@api_view(['POST'])
@login_required
def shopping_update(request) -> HttpResponse:
    """Change status of an ingredient (bought/to buy)."""
    ingredient_id = int(request.POST['ingredient_id'])
    ingredient = get_object_or_404(Ingredient, ingredient_id=ingredient_id)
    status = int(request.POST['action'])
    if UserShoppingList.objects.filter(user_id=request.user.id, ingredient=ingredient).exists():
        UserShoppingList.objects.filter(user_id=request.user.id, ingredient=ingredient).update(
            status=status
        )
    else:
        UserShoppingList(user_id=request.user.id, ingredient=ingredient, status=status).save()
    return HttpResponse('Success.')


@api_view(['POST'])
@login_required
def favorite_active_update(request):
    """Add/remove a recipe from user active/favorites recipes. Set all ingredients status to 'not bought'
    Used in choose, active and favorite views."""
    models_dict = {'favorites': UserFavoriteRecipe, 'active': UserActiveRecipe}
    model = models_dict[request.POST['model']]
    recipe_id = request.POST['recipe_id']
    if request.POST['action'] == 'add':
        existing_recipes = model.objects.filter(user_id=request.user.id).values_list('recipe_id', flat=True)
        if int(recipe_id) not in existing_recipes:
            model(user_id=request.user.id, recipe_id=recipe_id).save()
    elif request.POST['action'] == 'remove':
        model.objects.filter(user_id=request.user.id).filter(recipe_id=recipe_id).delete()
    if request.POST['model'] == 'active':
        UserShoppingList.objects.filter(user_id=request.user.id).update(status=0)
    return HttpResponse('Success')

mealprep/recipes/templates/recipes/active.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Active recipes - Easy Meals
{% endblock %}

{% block main %}
<div class="album py-5 bg-light">
    <div class="container">

        <div  data-id="active-favorite-title">
            <div class="d-flex justify-content-center align-items-center"><p class="navbar-brand">ACTIVE RECIPES</p></div>
        </div>

        {% if not recipes %}
        <div class="d-flex flex-column justify-content-center align-items-center">
            <img alt="..." class="img-fluid" src="/static/recipes/images/gif/confused_travolta.gif">
            <h5 class="mt-4">Nothing to see here, <a class="discover-link" href="{% url 'recipes:choose' %}">discover new recipes</a>.</h5>
        </div>
        {% endif %}

        <!--Individual recipe cards-->
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 row-cols-xl-3 row-cols-xxl-3 g-3">
            {% for recipe in recipes %}
            <div class="col" data-id="col_{{ recipe.recipe_id }}">
                <div class="card shadow-sm h-100 border border-2 border-success" data-id="card_{{ recipe.recipe_id }}">
                    <!--Favorites star-->
                    {% if recipe.recipe_id in favorite_recipes %}
                    <svg class="bi bi-star-fill position-absolute top-0 end-0" data-id="favorite_star_{{ recipe.recipe_id }}" fill="rgba(20,128,0,255)"
                         height="35" stroke="white" viewBox="0 0 16 16" width="35" xmlns="http://www.w3.org/2000/svg">
                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                    </svg>
                    {% else %}
                    <svg class="bi bi-star-fill position-absolute top-0 end-0" data-id="favorite_star_{{ recipe.recipe_id }}" fill="rgba(20,128,0,255)" height="35"
                         stroke="white" style="display: none" viewBox="0 0 16 16" width="35" xmlns="http://www.w3.org/2000/svg">
                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                    </svg>
                    {% endif %}
                    <!--Recipe image-->
                    <a href="{% url 'recipes:recipe' recipe.recipe_id %}">
                        <img alt="{{ recipe.recipe.title }} {{ recipe.recipe.subtitle }}"
                             class="card-img-top" src="/static/recipes/images/recipe-images-800w/{{ recipe.recipe.recipe_id_hash }}.jpg">
                    </a>
                    <!--Block under image for title, actions and short description-->
                    <div class="card-body d-flex flex-column justify-content-between">
                        <!--Recipe title-->
                        <a class="mb-3" href="{% url 'recipes:recipe' recipe.recipe_id %}">
                            <p class="card-title" data-id="grid-card-title">{{ recipe.recipe.title }} </p>
                            <p class="card-subtitle" data-id="grid-card-subtitle">{{ recipe.recipe.subtitle }}</p>
                        </a>
                        <!--Two buttons and prep time-->
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-toolbar">
                                <!--Active recipes buttons-->
                                <div data-id="div_remove_from_active_{{ recipe.recipe_id }}">
                                    <button class="btn btn-sm btn-outline-danger me-1" data-id="remove_from_active"
                                            data-page-type="active" data-recipe-id="{{ recipe.recipe_id }}">- active
                                    </button>
                                </div>
                                <!--Favorite recipes buttons-->
                                {% if recipe.recipe_id in favorite_recipes %}
                                <div data-id="div_add_to_favorites_{{ recipe.recipe_id }}" style="display:none">
                                    <button class="btn btn-sm btn-outline-success me-1" data-id="add_to_favorites"
                                            data-page-type="active" data-recipe-id="{{ recipe.recipe_id }}">+ favorites
                                    </button>
                                </div>
                                <div data-id="div_remove_from_favorites_{{ recipe.recipe_id }}">
                                    <button class="btn btn-sm btn-outline-danger me-1" data-id="remove_from_favorites"
                                            data-page-type="active" data-recipe-id="{{ recipe.recipe_id }}">- favorites
                                    </button>
                                </div>
                                {% else %}
                                <div data-id="div_add_to_favorites_{{ recipe.recipe_id }}">
                                    <button class="btn btn-sm btn-outline-success me-1" data-id="add_to_favorites"
                                            data-page-type="active" data-recipe-id="{{ recipe.recipe_id }}">+ favorites
                                    </button>
                                </div>
                                <div data-id="div_remove_from_favorites_{{ recipe.recipe_id }}" style="display:none">
                                    <button class="btn btn-sm btn-outline-danger me-1" data-id="remove_from_favorites"
                                            data-page-type="active" data-recipe-id="{{ recipe.recipe_id }}">- favorites
                                    </button>
                                </div>
                                {% endif %}
                            </div>
                            <!--Preparation time-->
                            <small class="text-muted">{{ recipe.recipe.time_total }} min</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %}

{% block script %}
<script src="/static/recipes/scripts/add-remove-buttons.js"></script>
{% endblock %}

mealprep/recipes/templates/recipes/favorite.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Favorite recipes - Easy Meals
{% endblock %}

{% block main %}
<div class="album py-5 bg-light">
    <div class="container">

        <div  data-id="active-favorite-title">
            <div class="d-flex justify-content-center align-items-center"><p class="navbar-brand">FAVORITE RECIPES</p></div>
        </div>

        {% if not favorite_recipes %}
        <div class="d-flex flex-column justify-content-center align-items-center">
            <img alt="..." class="img-fluid" src="/static/recipes/images/gif/confused_travolta.gif">
            <h5 class="mt-4">Nothing to see here, <a class="discover-link" href="{% url 'recipes:choose' %}">discover new recipes</a>.</h5>
        </div>
        {% endif %}

        <!--Individual recipe cards-->
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 row-cols-xl-3 row-cols-xxl-3 g-3">
            {% for recipe in favorite_recipes %}
            <div class="col" data-id="col_{{ recipe.recipe.recipe_id }}">
                {% if recipe.recipe.recipe_id in active_recipes %}
                <div class="card shadow-sm h-100 border border-2 border-success"
                     data-id="card_{{ recipe.recipe.recipe_id }}">
                    {% else %}
                    <div class="card shadow-sm h-100" data-id="card_{{ recipe.recipe.recipe_id }}">
                        {% endif %}
                        <!--Favorite star-->
                        <svg class="bi bi-star-fill position-absolute top-0 end-0"
                             data-id="favorite_star_{{ recipe.recipe_id }}" fill="rgba(20,128,0,255)"
                             height="35" stroke="white" viewBox="0 0 16 16" width="35"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                        </svg>
                        <!--Recipe image-->
                        <a href="{% url 'recipes:recipe' recipe.recipe_id %}">
                            <img alt="{{ recipe.recipe.title }} {{ recipe.recipe.subtitle }}"
                                 class="card-img-top"
                                 src="/static/recipes/images/recipe-images-800w/{{ recipe.recipe.recipe_id_hash }}.jpg">
                        </a>
                        <!--Block under image for title, actions and short description-->
                        <div class="card-body d-flex flex-column justify-content-between">
                            <!--Recipe title-->
                            <a class="mb-3" href="{% url 'recipes:recipe' recipe.recipe_id %}">
                                <p class="card-title" data-id="grid-card-title">{{ recipe.recipe.title }} </p>
                                <p class="card-subtitle" data-id="grid-card-subtitle">{{ recipe.recipe.subtitle }}</p>
                            </a>
                            <!--Two buttons and prep time-->
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-toolbar">
                                    <!--Active recipes buttons-->
                                    {% if recipe.recipe_id in active_recipes %}
                                    <div data-id="div_add_to_active_{{ recipe.recipe_id }}" style="display:none">
                                        <button class="btn btn-sm btn-outline-success me-1" data-id="add_to_active"
                                                data-page-type="favorites" data-recipe-id="{{ recipe.recipe_id }}">+
                                            active
                                        </button>
                                    </div>
                                    <div data-id="div_remove_from_active_{{ recipe.recipe_id }}">
                                        <button class="btn btn-sm btn-outline-danger me-1" data-id="remove_from_active"
                                                data-page-type="favorites" data-recipe-id="{{ recipe.recipe_id }}">-
                                            active
                                        </button>
                                    </div>
                                    {% else %}
                                    <div data-id="div_add_to_active_{{ recipe.recipe_id }}">
                                        <button class="btn btn-sm btn-outline-success me-1" data-id="add_to_active"
                                                data-page-type="favorites" data-recipe-id="{{ recipe.recipe_id }}">+
                                            active
                                        </button>
                                    </div>
                                    <div data-id="div_remove_from_active_{{ recipe.recipe_id }}" style="display:none">
                                        <button class="btn btn-sm btn-outline-danger me-1" data-id="remove_from_active"
                                                data-page-type="favorites" data-recipe-id="{{ recipe.recipe_id }}">-
                                            active
                                        </button>
                                    </div>
                                    {% endif %}
                                    <!--Favorite recipes buttons-->
                                    <div data-id="div_remove_from_favorites_{{ recipe.recipe_id }}">
                                        <button class="btn btn-sm btn-outline-danger me-1"
                                                data-id="remove_from_favorites" data-page-type="favorites"
                                                data-recipe-id="{{ recipe.recipe_id }}">- favorites
                                        </button>
                                    </div>
                                </div>
                                <!--Preparation time-->
                                <small class="text-muted">{{ recipe.recipe.time_total }} min</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>

    </div>
</div>
    {% endblock %}


{% block script %}
<script src="/static/recipes/scripts/add-remove-buttons.js"></script>
{% endblock %}

mealprep/recipes/templates/recipes/shopping.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Shopping - Easy Meals
{% endblock %}

{% block main %}
<div class="album py-5 bg-light">
    <div class="container">

        {% if not ingr_dict %}
        <div class="d-flex flex-column justify-content-center align-items-center">
            <img alt="..." class="img-fluid" src="/static/recipes/images/gif/confused_travolta.gif">
            <h5 class="mt-4">Nothing to see here, <a class="discover-link" href="{% url 'recipes:choose' %}">discover new recipes</a>.</h5>
        </div>
        {% endif %}

        <div class="accordion" id="accordionPanelsStayOpenExample">
            <!--Each category-->
            {% for category, ingredients in ingr_dict.items %}
            <div class="accordion-item">
                <!--Button with category name-->
                <h2 class="accordion-header" id="panelsStayOpen-heading{{ forloop.counter }}">
                    <button aria-controls="panelsStayOpen-collapse{{ forloop.counter }}" aria-expanded="true" class="accordion-button"
                            data-bs-target="#panelsStayOpen-collapse{{ forloop.counter }}" data-bs-toggle="collapse"
                            type="button">
                        {{ category }}
                    </button>
                </h2>
                <div aria-labelledby="panelsStayOpen-heading{{ forloop.counter }}" class="accordion-collapse collapse show"
                     id="panelsStayOpen-collapse{{ forloop.counter }}">
                    <div class="accordion-body">

                        <!--Each individual ingredient-->
                        <div class="row row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-3">
                            {% for ingredient in ingredients %}
                            <div>
                                <a data-ingredient-id="{{ ingredient.ingredient_id }}" data-id="ingredient" href="#">
                                    {% if ingredient.ingredient_id in bought_ingredients %}
                                    <div class="card shadow-sm h-100 justify-content-center align-items-center border border-2 border-success"
                                        data-ingredient-id="ingredient_{{ ingredient.ingredient_id }}"
                                        style="background: rgba(228, 250, 191, 255)">
                                    {% else %}
                                    <div class="card shadow-sm h-100 justify-content-center align-items-center" data-ingredient-id="ingredient_{{ ingredient.ingredient_id }}">
                                            {% endif %}
                                            <!--Recipe image-->
                                            <img alt="{{ ingredient.ingredient__ingredient_name }}" class="ingredient_image"
                                                 src="/static/recipes/images/ingredient-images/{{ ingredient.ingredient__ingredient_id_hash }}.png">
                                            {% load ingredient_formatting %}
                                            <!--Block under image for title, actions and short description-->
                                            <p class="card-title mx-2" data-id="recipe-card-title"> {{ ingredient.ingredient__ingredient_name }}</p>
                                            <p class="card-subtitle" data-id="recipe-card-subtitle">{{ ingredient.quantity|format_ingr_quant }} {{ ingredient.quantity_unit|pluralize_ingr:ingredient.quantity }}</p>
                                        </div>
                                </a>
                            </div>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %}


{% block script %}
<!--Change color and status of ingredient-->
<script src="/static/recipes/scripts/shopping-ingredient-state.js"></script>
{% endblock %}