mealprep/accounts/urls.py
from django.urls import path
from django.contrib.auth import views

from . import views as custom_views

app_name = 'accounts'

urlpatterns = [
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path('login/', custom_views.user_login, name='user_login'),
]

mealprep/mealprep/urls.py
import os

from django.contrib import admin
from django.urls import path, include
from recipes.views import custom_handler404


handler404 = custom_handler404

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('recipes.urls')),
    path(r'{}/'.format(os.environ.get('ADMIN_ROUTE')), admin.site.urls),
#    path('admin/', admin.site.urls),
]

mealprep/recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.index, name='index'),
    path('choose', views.choose, name='choose'),
    path('active', views.active, name='active'),
    path('shopping', views.shopping, name='shopping'),
    path('favorite', views.favorite, name='favorite'),
    path('recipe/<int:recipe_id>/', views.recipe, name='recipe'),
    path('favorite_active_update', views.favorite_active_update, name='favorite_active_update'),
    path('shopping_update', views.shopping_update, name='shopping_update')
]

mealprep/recipes/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db.models.functions import Concat
from django.db.models import Sum, Value
from django.db import models


# Recipe related tables
class Recipe(models.Model):

    class DifficultyType(models.TextChoices):
        FACILE = 'Facile'
        INTERMEDIAIRE = 'Intérmediaire'
        DIFFICILE = 'Difficile'

    recipe_id = models.AutoField(primary_key=True)
    recipe_id_hash = models.BigIntegerField()
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=200)
    time_total = models.SmallIntegerField()
    time_prep = models.SmallIntegerField()
    difficulty = models.CharField(max_length=20, choices=DifficultyType.choices)
    meal_type = models.CharField(max_length=50)
    recipe_json = models.CharField(max_length=10000)

    class Meta:
        managed = False
        db_table = 'recipe'

    def __str__(self):
        return f'{self.title} {self.subtitle}'


class Ingredient(models.Model):
    ingredient_id = models.AutoField(primary_key=True)
    ingredient_id_hash = models.BigIntegerField()
    ingredient_name = models.CharField(max_length=200)
    ingredient_class = models.CharField(max_length=200)
    ingredient_type = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'ingredient'

    def __str__(self):
        return self.ingredient_name


class Tag(models.Model):
    tag_id = models.AutoField(primary_key=True)
    tag_name = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'tag'

    def __str__(self):
        return f'{self.tag_name}'


class Tool(models.Model):
    tool_id = models.AutoField(primary_key=True)
    tool_name = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'tool'

    def __str__(self):
        return f'{self.tool_name}'


class RecipeIngredient(models.Model):
    id = models.AutoField(primary_key=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.RESTRICT)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.RESTRICT)
    quantity = models.FloatField()
    quantity_unit = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'recipe_ingredient'

    def __str__(self):
        return f'Recipe: {self.recipe}, ingredient: {self.ingredient}'


class RecipeNutrValue(models.Model):
    recipe = models.OneToOneField(Recipe, on_delete=models.RESTRICT, primary_key=True)
    energie_kj = models.FloatField()
    energie_kcal = models.FloatField()
    matieres_grasses = models.FloatField()
    acides_gras_satures = models.FloatField()
    glucides = models.FloatField()
    sucres = models.FloatField()
    proteines = models.FloatField()
    sel = models.FloatField()

    class Meta:
        managed = False
        db_table = 'recipe_nutr_value'


class RecipeTag(models.Model):
    id = models.AutoField(primary_key=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.RESTRICT)
    tag = models.ForeignKey('Tag', on_delete=models.RESTRICT)

    class Meta:
        managed = False
        db_table = 'recipe_tag'


class RecipeTool(models.Model):
    id = models.AutoField(primary_key=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.RESTRICT)
    tool = models.ForeignKey(Tool, on_delete=models.RESTRICT)

    class Meta:
        managed = False
        db_table = 'recipe_tool'


# User related tables
class User(AbstractUser):
    pass


class UserShoppingList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, null=True)
    status = models.SmallIntegerField(default=0)


class UserActiveRecipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, null=True)


class UserFavoriteRecipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, null=True)

mealprep/recipes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import HttpResponse
from rest_framework.decorators import api_view

from .models import Ingredient, Recipe, RecipeIngredient, UserActiveRecipe, UserFavoriteRecipe, UserShoppingList


@api_view(['GET'])
def custom_handler404(request, exception):
    return render(request, 'recipes/404.html', status=404)


@api_view(['GET'])
@login_required
def index(request) -> redirect:
    """Redirect from index to active."""
    return redirect('recipes:active')


@api_view(['GET'])
@login_required
def choose(request) -> render:
    """List all available recipes sorted my meal type. Can be filtered by total preparation time or meal type."""
    recipes = Recipe.objects.all().order_by('meal_type')
    active_recipes = UserActiveRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    favorite_recipes = UserFavoriteRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    return render(request, 'recipes/choose.html',
                  {
                      'recipes': recipes,
                      'active_recipes': active_recipes,
                      'favorite_recipes': favorite_recipes,
                      'meal_types': recipes.order_by('meal_type').values_list('meal_type', flat=True).distinct(),
                      'prep_times': recipes.order_by('time_total').values_list('time_total', flat=True).distinct()
                  })


@api_view(['GET'])
@login_required
def active(request) -> render:
    """List of user active recipes."""
    recipes = UserActiveRecipe.objects.filter(user_id=request.user.id).select_related('recipe')
    favorite_recipes = UserFavoriteRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    return render(
        request, 'recipes/active.html', {'recipes': recipes, 'favorite_recipes': favorite_recipes}
    )


@api_view(['GET'])
@login_required
def favorite(request) -> render:
    """List of user favorite recipes."""
    favorite_recipes = UserFavoriteRecipe.objects.filter(user_id=request.user.id).select_related('recipe')
    active_recipes = UserActiveRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    return render(
        request, 'recipes/favorite.html', {'favorite_recipes': favorite_recipes, 'active_recipes': active_recipes}
    )


@api_view(['GET'])
@login_required
def shopping(request) -> render:
    """List of ingredients to buy for active recipe(s). Sorted by ingredient category."""
    recipes_list = UserActiveRecipe.objects.filter(user_id=request.user.id).values_list('recipe_id', flat=True)
    ingredients = RecipeIngredient.objects.filter(recipe_id__in=recipes_list).select_related('ingredient')
    ingredients = ingredients.values(
        'ingredient_id', 'ingredient__ingredient_id_hash', 'ingredient__ingredient_name', 'ingredient__ingredient_class',
        'quantity_unit'
    ).order_by().annotate(quantity=Sum("quantity"))
    categories = ["Légumes", "Fruits", "Herbes", "Végétarien", "Conserves", "Graines et Pâtes", "Épices",
                  "Laitier", "Salades", "Pains", "Autre"]
    ingr_dict = {i: ingredients.filter(ingredient__ingredient_class=i) for i in categories if ingredients.filter(ingredient__ingredient_class=i)}
    bought_ingredients = UserShoppingList.objects.filter(user_id=request.user.id, status=1).values_list('ingredient_id', flat=True)
    return render(request, 'recipes/shopping.html', {
        'ingr_dict': ingr_dict, 'categories': categories, 'bought_ingredients': bought_ingredients
    })


@api_view(['GET'])
@login_required
def recipe(request, recipe_id: int) -> render:
    """Recipe page with description, list of ingredients and instructions."""
    recipe_dict = eval(get_object_or_404(Recipe, recipe_id=recipe_id).recipe_json)
    nutr_val_cat = ['Énergie (kJ)', 'Énergie (kcal)', 'Matières grasses', 'dont acides gras saturés',
                    'Glucides', 'dont sucres', 'Protéines', 'Sel']
    unit = ['kJ', 'kcal'] + ['g'] * 5
    nutr_val = zip(nutr_val_cat, recipe_dict['nutritional_val'], unit)
    active_recipes = UserActiveRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    favorite_recipes = UserFavoriteRecipe.objects.filter(user_id=request.user.id).values_list('recipe', flat=True)
    return render(request, 'recipes/recipe.html',
                  {'recipe': recipe_dict,
                   'nutr_val': nutr_val,
                   'active_recipe': recipe_id in active_recipes,
                   'favorite_recipe': recipe_id in favorite_recipes
                   })


@api_view(['POST'])
@login_required
def shopping_update(request) -> HttpResponse:
    """Change status of an ingredient (bought/to buy)."""
    ingredient_id = int(request.POST['ingredient_id'])
    ingredient = get_object_or_404(Ingredient, ingredient_id=ingredient_id)
    status = int(request.POST['action'])
    if UserShoppingList.objects.filter(user_id=request.user.id, ingredient=ingredient).exists():
        UserShoppingList.objects.filter(user_id=request.user.id, ingredient=ingredient).update(
            status=status
        )
    else:
        UserShoppingList(user_id=request.user.id, ingredient=ingredient, status=status).save()
    return HttpResponse('Success.')


@api_view(['POST'])
@login_required
def favorite_active_update(request):
    """Add/remove a recipe from user active/favorites recipes. Set all ingredients status to 'not bought'
    Used in choose, active and favorite views."""
    models_dict = {'favorites': UserFavoriteRecipe, 'active': UserActiveRecipe}
    model = models_dict[request.POST['model']]
    recipe_id = request.POST['recipe_id']
    if request.POST['action'] == 'add':
        existing_recipes = model.objects.filter(user_id=request.user.id).values_list('recipe_id', flat=True)
        if int(recipe_id) not in existing_recipes:
            model(user_id=request.user.id, recipe_id=recipe_id).save()
    elif request.POST['action'] == 'remove':
        model.objects.filter(user_id=request.user.id).filter(recipe_id=recipe_id).delete()
    if request.POST['model'] == 'active':
        UserShoppingList.objects.filter(user_id=request.user.id).update(status=0)
    return HttpResponse('Success')

mealprep/recipes/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1, width=device-width">
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🍜</text></svg>">
        <link rel="stylesheet" crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" type="text/css">
        <link rel="stylesheet" href="{% static 'recipes/styles/styles.css' %}">
        <!--Stylesheet for filters on Choose page-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.css">
        <!--Highlighting active page-->
        <style>
            #\{{ request.path }} {
                    color: green;
                    font-weight: bold;
            }

            @media (min-width: 762px) {
                #\{{ request.path }} {
                    color: green;
                    font-weight: bold;
                    border-bottom: 0.1rem solid green;
                }
            }
        </style>
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <!--Navigation bar-->
        <nav class="bg-light border navbar sticky-top navbar-expand-md navbar-light">
            <div class="container-fluid">
                <!--Logo-->
                <a class="navbar-brand" href="/">EASY MEALS</a>
                <!--Navbar toggler for small screens-->
                <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbar" data-bs-toggle="collapse" type="button">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!--Page choice buttons-->
                <div class="collapse navbar-collapse" id="navbar">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item" ><a class="nav-link" id="/choose" href="{% url 'recipes:choose' %}">Choose</a></li>
                        <li class="nav-item"><a class="nav-link" id="/active" href="{% url 'recipes:active' %}">Active</a></li>
                        <li class="nav-item"><a class="nav-link" id="/favorite" href="{% url 'recipes:favorite' %}">Favorites</a></li>
                        <li class="nav-item"><a class="nav-link" id="/shopping" href="{% url 'recipes:shopping' %}">Shopping</a></li>
                    </ul>
                    <!--Logout button-->
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out - {{ request.user.username }}</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <main>{% block main %}{% endblock %}</main>

        <footer class="mb-5 small text-center text-muted"></footer>

        <script src="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js" integrity="sha512-aUhL2xOCrpLEuGD5f6tgHbLYEXRpYZ8G5yD+WlFrXrPy2IrWBlu6bih5C9H6qGsgqnU6mgx6KtU8TreHpASprw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"></script>

        {% block script %}{% endblock %}

    </body>

</html>