mealprep/accounts/urls.py
from django.urls import path
from django.contrib.auth import views

from . import views as custom_views

app_name = 'accounts'

urlpatterns = [
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path('login/', custom_views.user_login, name='user_login'),
]

mealprep/mealprep/urls.py
import os

from django.contrib import admin
from django.urls import path, include
from recipes.views import custom_handler404


handler404 = custom_handler404

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('recipes.urls')),
    path(r'{}/'.format(os.environ.get('ADMIN_ROUTE')), admin.site.urls),
#    path('admin/', admin.site.urls),
]

mealprep/recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.index, name='index'),
    path('choose', views.choose, name='choose'),
    path('active', views.active, name='active'),
    path('shopping', views.shopping, name='shopping'),
    path('favorite', views.favorite, name='favorite'),
    path('recipe/<int:recipe_id>/', views.recipe, name='recipe'),
    path('favorite_active_update', views.favorite_active_update, name='favorite_active_update'),
    path('shopping_update', views.shopping_update, name='shopping_update')
]

mealprep/accounts/models.py
from django.db import models

# Create your models here.

mealprep/accounts/forms.py
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Invisible


class LoginForm(forms.Form):
    username = forms.CharField(max_length=69)
    password = forms.CharField(max_length=69)
    captcha = ReCaptchaField(widget=ReCaptchaV2Invisible)

mealprep/accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import get_user_model
from django.shortcuts import redirect, render
from rest_framework.decorators import api_view

from .forms import LoginForm


User = get_user_model()


@api_view(['GET', 'POST'])
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                # Save session as cookie to login the user
                login(request, user)
                return redirect('recipes:choose')
            else:
                # Incorrect credentials
                return render(request, 'accounts/login.html',
                              {'error_message': 'You have entered an invalid username or password',
                               'form': form})
        else:
            form = LoginForm()
            return render(request, 'accounts/login.html', {'error_message': "Invalid CAPTCHA", 'form': form})

    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})

mealprep/accounts/templates/accounts/login.html
<!doctype html>
{% load static %}


<html lang="fr">

  <head>
      <meta charset="utf-8">
      <meta content="width=device-width, initial-scale=1" name="viewport">
      <meta content="Mark Otto, Jacob Thornton, and Bootstrap contributors" name="author">
      <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🍜</text></svg>">
      <title>Signin - EasyMeals</title>

      <link href="https://getbootstrap.com/docs/5.0/examples/sign-in/" rel="canonical">

      <link href="{% static 'accounts/styles.css' %}" rel="stylesheet">

      <!-- Bootstrap core CSS -->
      <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">

      <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

      </style>

  </head>

  <body class="text-center">
    <main class="form-signin">

        {% if error_message %}
        <div class="alert alert-danger mb-5" role="alert">
            {{ error_message }}
        </div>
        {% endif %}

            <h1 class="mb-5">EASY MEALS</h1>
            {% load widget_tweaks %}

            <form action="{% url 'accounts:user_login' %}" method="post">
              {% csrf_token %}

                <div class="form-floating">
                    {% render_field form.username class="form-control" id="floatingInput" name="username" placeholder="name@example.com" type="text" %}
                    <label for="floatingInput">Username</label>
                </div>

                <div class="form-floating mt-1">
                    {% render_field form.password class="form-control" id="floatingPassword" name="password" placeholder="Password" type="password" %}
                    <label for="floatingPassword">Password</label>
                </div>

                <div class="form-floating my-2">
                {% render_field form.captcha %}
                </div>

            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>

        </form>
    </main>
  </body>

</html>